# Versão do docker-compose
version: '3.8'

# Lista de serviços (containers)
services:
  # O nosso serviço de banco de dados
  db:
    image: postgis/postgis:15-3.3
    container_name: postgres_braga
    environment:
      - POSTGRES_USER=braga_user
      - POSTGRES_PASSWORD=braga_password
      - POSTGRES_DB=braga_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # O nosso serviço da aplicação Streamlit
  dashboard:
    build: .
    container_name: streamlit_dashboard
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - db